export const SET_BOOKS = 'SET_BOOKS',
  SET_ADVANCED_REQUEST = 'SET_ADVANCED_REQUEST',
  SET_BOOK_VOLUME = 'SET_BOOK_VOLUME',
  SET_SIDEBAR = 'SET_SIDEBAR',
  SET_SAVE = 'SET_SAVE',
  SET_UNSAVE = 'SET_UNSAVE';